//go:build go1.22

// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package contract

import (
	"fmt"
	"net/http"
)

// Defines values for AssignmentConventionProfileCatalogPath.
const (
	DotGithubagentProfilesYml AssignmentConventionProfileCatalogPath = ".github/agent-profiles.yml"
)

// Valid indicates whether the value is a known member of the AssignmentConventionProfileCatalogPath enum.
func (e AssignmentConventionProfileCatalogPath) Valid() bool {
	switch e {
	case DotGithubagentProfilesYml:
		return true
	default:
		return false
	}
}

// Defines values for AssignmentConventionProfileSchemaVersion.
const (
	AssignmentConventionProfileSchemaVersionN1 AssignmentConventionProfileSchemaVersion = 1
)

// Valid indicates whether the value is a known member of the AssignmentConventionProfileSchemaVersion enum.
func (e AssignmentConventionProfileSchemaVersion) Valid() bool {
	switch e {
	case AssignmentConventionProfileSchemaVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for AssignmentConventionVersion.
const (
	AssignmentConventionVersionN1 AssignmentConventionVersion = 1
)

// Valid indicates whether the value is a known member of the AssignmentConventionVersion enum.
func (e AssignmentConventionVersion) Valid() bool {
	switch e {
	case AssignmentConventionVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for AssignmentPolicyAuthority.
const (
	BranchDraftPr AssignmentPolicyAuthority = "branch-draft-pr"
)

// Valid indicates whether the value is a known member of the AssignmentPolicyAuthority enum.
func (e AssignmentPolicyAuthority) Valid() bool {
	switch e {
	case BranchDraftPr:
		return true
	default:
		return false
	}
}

// Defines values for AssignmentPolicyCommandTemplate.
const (
	AgentAssignProfileIdProfileRevisionAuthorityBranchDraftPr AssignmentPolicyCommandTemplate = "/agent assign {profile_id}@{profile_revision} authority=branch-draft-pr"
)

// Valid indicates whether the value is a known member of the AssignmentPolicyCommandTemplate enum.
func (e AssignmentPolicyCommandTemplate) Valid() bool {
	switch e {
	case AgentAssignProfileIdProfileRevisionAuthorityBranchDraftPr:
		return true
	default:
		return false
	}
}

// Defines values for AssignmentPolicyEvent.
const (
	IssueCommentCreated AssignmentPolicyEvent = "issue_comment.created"
)

// Valid indicates whether the value is a known member of the AssignmentPolicyEvent enum.
func (e AssignmentPolicyEvent) Valid() bool {
	switch e {
	case IssueCommentCreated:
		return true
	default:
		return false
	}
}

// Defines values for AssignmentPolicyRequiredRoles.
const (
	Admin    AssignmentPolicyRequiredRoles = "admin"
	Maintain AssignmentPolicyRequiredRoles = "maintain"
)

// Valid indicates whether the value is a known member of the AssignmentPolicyRequiredRoles enum.
func (e AssignmentPolicyRequiredRoles) Valid() bool {
	switch e {
	case Admin:
		return true
	case Maintain:
		return true
	default:
		return false
	}
}

// Defines values for AssignmentPolicySourceKind.
const (
	Issue AssignmentPolicySourceKind = "issue"
)

// Valid indicates whether the value is a known member of the AssignmentPolicySourceKind enum.
func (e AssignmentPolicySourceKind) Valid() bool {
	switch e {
	case Issue:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeInternalError    ErrorCode = "internal_error"
	ErrorCodeMethodNotAllowed ErrorCode = "method_not_allowed"
	ErrorCodeNotFound         ErrorCode = "not_found"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeInternalError:
		return true
	case ErrorCodeMethodNotAllowed:
		return true
	case ErrorCodeNotFound:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ProfileRevisionPolicyDefaultBranchAncestor.
const (
	True ProfileRevisionPolicyDefaultBranchAncestor = true
)

// Valid indicates whether the value is a known member of the ProfileRevisionPolicyDefaultBranchAncestor enum.
func (e ProfileRevisionPolicyDefaultBranchAncestor) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// Defines values for ProfileRevisionPolicyFormat.
const (
	Full40CharacterSha ProfileRevisionPolicyFormat = "full-40-character-sha"
)

// Valid indicates whether the value is a known member of the ProfileRevisionPolicyFormat enum.
func (e ProfileRevisionPolicyFormat) Valid() bool {
	switch e {
	case Full40CharacterSha:
		return true
	default:
		return false
	}
}

// AssignmentConvention defines model for AssignmentConvention.
type AssignmentConvention struct {
	Assignment           AssignmentPolicy                         `json:"assignment"`
	ProfileCatalogPath   AssignmentConventionProfileCatalogPath   `json:"profile_catalog_path"`
	ProfileSchemaVersion AssignmentConventionProfileSchemaVersion `json:"profile_schema_version"`
	Version              AssignmentConventionVersion              `json:"version"`
}

// AssignmentConventionProfileCatalogPath defines model for AssignmentConvention.ProfileCatalogPath.
type AssignmentConventionProfileCatalogPath string

// AssignmentConventionProfileSchemaVersion defines model for AssignmentConvention.ProfileSchemaVersion.
type AssignmentConventionProfileSchemaVersion int

// AssignmentConventionVersion defines model for AssignmentConvention.Version.
type AssignmentConventionVersion int

// AssignmentPolicy defines model for AssignmentPolicy.
type AssignmentPolicy struct {
	Authority       AssignmentPolicyAuthority       `json:"authority"`
	CommandTemplate AssignmentPolicyCommandTemplate `json:"command_template"`
	Event           AssignmentPolicyEvent           `json:"event"`
	ProfileRevision ProfileRevisionPolicy           `json:"profile_revision"`
	RequiredRoles   []AssignmentPolicyRequiredRoles `json:"required_roles"`
	SourceKind      AssignmentPolicySourceKind      `json:"source_kind"`
}

// AssignmentPolicyAuthority defines model for AssignmentPolicy.Authority.
type AssignmentPolicyAuthority string

// AssignmentPolicyCommandTemplate defines model for AssignmentPolicy.CommandTemplate.
type AssignmentPolicyCommandTemplate string

// AssignmentPolicyEvent defines model for AssignmentPolicy.Event.
type AssignmentPolicyEvent string

// AssignmentPolicyRequiredRoles defines model for AssignmentPolicy.RequiredRoles.
type AssignmentPolicyRequiredRoles string

// AssignmentPolicySourceKind defines model for AssignmentPolicy.SourceKind.
type AssignmentPolicySourceKind string

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for Error.Code.
type ErrorCode string

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// ProfileRevisionPolicy defines model for ProfileRevisionPolicy.
type ProfileRevisionPolicy struct {
	DefaultBranchAncestor ProfileRevisionPolicyDefaultBranchAncestor `json:"default_branch_ancestor"`
	Format                ProfileRevisionPolicyFormat                `json:"format"`
}

// ProfileRevisionPolicyDefaultBranchAncestor defines model for ProfileRevisionPolicy.DefaultBranchAncestor.
type ProfileRevisionPolicyDefaultBranchAncestor bool

// ProfileRevisionPolicyFormat defines model for ProfileRevisionPolicy.Format.
type ProfileRevisionPolicyFormat string

// InternalError defines model for InternalError.
type InternalError = Error

// MethodNotAllowed defines model for MethodNotAllowed.
type MethodNotAllowed = Error

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Check process liveness
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// HeadHealth Check liveness without a response body
	// (HEAD /health)
	HeadHealth(w http.ResponseWriter, r *http.Request)
	// GetAssignmentConvention Read the supported GitHub assignment convention
	// (GET /v1/assignment-convention)
	GetAssignmentConvention(w http.ResponseWriter, r *http.Request)
	// HeadAssignmentConvention Check convention availability without a response body
	// (HEAD /v1/assignment-convention)
	HeadAssignmentConvention(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HeadHealth operation middleware
func (siw *ServerInterfaceWrapper) HeadHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HeadHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAssignmentConvention operation middleware
func (siw *ServerInterfaceWrapper) GetAssignmentConvention(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAssignmentConvention(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HeadAssignmentConvention operation middleware
func (siw *ServerInterfaceWrapper) HeadAssignmentConvention(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HeadAssignmentConvention(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodHead+" "+options.BaseURL+"/health", wrapper.HeadHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/assignment-convention", wrapper.GetAssignmentConvention)
	m.HandleFunc(http.MethodHead+" "+options.BaseURL+"/v1/assignment-convention", wrapper.HeadAssignmentConvention)

	return m
}
