// Package agentscontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package agentscontract

// Defines values for BootstrapPreviewState.
const (
	BootstrapPreviewStateConflict  BootstrapPreviewState = "conflict"
	BootstrapPreviewStateReady     BootstrapPreviewState = "ready"
	BootstrapPreviewStateUnchanged BootstrapPreviewState = "unchanged"
)

// Valid indicates whether the value is a known member of the BootstrapPreviewState enum.
func (e BootstrapPreviewState) Valid() bool {
	switch e {
	case BootstrapPreviewStateConflict:
		return true
	case BootstrapPreviewStateReady:
		return true
	case BootstrapPreviewStateUnchanged:
		return true
	default:
		return false
	}
}

// Defines values for BootstrapPreviewFileStatus.
const (
	BootstrapPreviewFileStatusConflict  BootstrapPreviewFileStatus = "conflict"
	BootstrapPreviewFileStatusCreate    BootstrapPreviewFileStatus = "create"
	BootstrapPreviewFileStatusUnchanged BootstrapPreviewFileStatus = "unchanged"
	BootstrapPreviewFileStatusUpdate    BootstrapPreviewFileStatus = "update"
)

// Valid indicates whether the value is a known member of the BootstrapPreviewFileStatus enum.
func (e BootstrapPreviewFileStatus) Valid() bool {
	switch e {
	case BootstrapPreviewFileStatusConflict:
		return true
	case BootstrapPreviewFileStatusCreate:
		return true
	case BootstrapPreviewFileStatusUnchanged:
		return true
	case BootstrapPreviewFileStatusUpdate:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeAccessDenied          ErrorCode = "access_denied"
	ErrorCodeGithubUnavailable     ErrorCode = "github_unavailable"
	ErrorCodeInternalError         ErrorCode = "internal_error"
	ErrorCodeInvalidRequest        ErrorCode = "invalid_request"
	ErrorCodeMethodNotAllowed      ErrorCode = "method_not_allowed"
	ErrorCodeNotFound              ErrorCode = "not_found"
	ErrorCodeRateLimited           ErrorCode = "rate_limited"
	ErrorCodeRepositoryUnavailable ErrorCode = "repository_unavailable"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeAccessDenied:
		return true
	case ErrorCodeGithubUnavailable:
		return true
	case ErrorCodeInternalError:
		return true
	case ErrorCodeInvalidRequest:
		return true
	case ErrorCodeMethodNotAllowed:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeRateLimited:
		return true
	case ErrorCodeRepositoryUnavailable:
		return true
	default:
		return false
	}
}

// BootstrapDiagnostic defines model for BootstrapDiagnostic.
type BootstrapDiagnostic struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	Path    string `json:"path"`
}

// BootstrapPreview defines model for BootstrapPreview.
type BootstrapPreview struct {
	BaseRevision  string                 `json:"base_revision"`
	DefaultBranch string                 `json:"default_branch"`
	Diagnostics   []BootstrapDiagnostic  `json:"diagnostics"`
	Diff          string                 `json:"diff"`
	Digest        string                 `json:"digest"`
	Files         []BootstrapPreviewFile `json:"files"`
	Private       bool                   `json:"private"`
	Repository    string                 `json:"repository"`
	State         BootstrapPreviewState  `json:"state"`
}

// BootstrapPreviewState defines model for BootstrapPreview.State.
type BootstrapPreviewState string

// BootstrapPreviewFile defines model for BootstrapPreviewFile.
type BootstrapPreviewFile struct {
	BaseSha *string                    `json:"base_sha"`
	Content string                     `json:"content"`
	Path    string                     `json:"path"`
	Sha256  *string                    `json:"sha256"`
	Status  BootstrapPreviewFileStatus `json:"status"`
}

// BootstrapPreviewFileStatus defines model for BootstrapPreviewFile.Status.
type BootstrapPreviewFileStatus string

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for Error.Code.
type ErrorCode string

// InternalError defines model for InternalError.
type InternalError = Error

// MethodNotAllowed defines model for MethodNotAllowed.
type MethodNotAllowed = Error
