// Package agentscontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package agentscontract

import (
	"time"
)

// Defines values for AssignmentRequestState.
const (
	Blocked     AssignmentRequestState = "blocked"
	Cancelled   AssignmentRequestState = "cancelled"
	Completed   AssignmentRequestState = "completed"
	Failed      AssignmentRequestState = "failed"
	Proposal    AssignmentRequestState = "proposal"
	Queued      AssignmentRequestState = "queued"
	Requested   AssignmentRequestState = "requested"
	Running     AssignmentRequestState = "running"
	Unavailable AssignmentRequestState = "unavailable"
)

// Valid indicates whether the value is a known member of the AssignmentRequestState enum.
func (e AssignmentRequestState) Valid() bool {
	switch e {
	case Blocked:
		return true
	case Cancelled:
		return true
	case Completed:
		return true
	case Failed:
		return true
	case Proposal:
		return true
	case Queued:
		return true
	case Requested:
		return true
	case Running:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for BootstrapPreviewState.
const (
	BootstrapPreviewStateConflict  BootstrapPreviewState = "conflict"
	BootstrapPreviewStateReady     BootstrapPreviewState = "ready"
	BootstrapPreviewStateUnchanged BootstrapPreviewState = "unchanged"
)

// Valid indicates whether the value is a known member of the BootstrapPreviewState enum.
func (e BootstrapPreviewState) Valid() bool {
	switch e {
	case BootstrapPreviewStateConflict:
		return true
	case BootstrapPreviewStateReady:
		return true
	case BootstrapPreviewStateUnchanged:
		return true
	default:
		return false
	}
}

// Defines values for BootstrapPreviewFileStatus.
const (
	BootstrapPreviewFileStatusConflict  BootstrapPreviewFileStatus = "conflict"
	BootstrapPreviewFileStatusCreate    BootstrapPreviewFileStatus = "create"
	BootstrapPreviewFileStatusUnchanged BootstrapPreviewFileStatus = "unchanged"
	BootstrapPreviewFileStatusUpdate    BootstrapPreviewFileStatus = "update"
)

// Valid indicates whether the value is a known member of the BootstrapPreviewFileStatus enum.
func (e BootstrapPreviewFileStatus) Valid() bool {
	switch e {
	case BootstrapPreviewFileStatusConflict:
		return true
	case BootstrapPreviewFileStatusCreate:
		return true
	case BootstrapPreviewFileStatusUnchanged:
		return true
	case BootstrapPreviewFileStatusUpdate:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeAccessDenied          ErrorCode = "access_denied"
	ErrorCodeGithubUnavailable     ErrorCode = "github_unavailable"
	ErrorCodeInternalError         ErrorCode = "internal_error"
	ErrorCodeInvalidRequest        ErrorCode = "invalid_request"
	ErrorCodeMethodNotAllowed      ErrorCode = "method_not_allowed"
	ErrorCodeNotFound              ErrorCode = "not_found"
	ErrorCodeRateLimited           ErrorCode = "rate_limited"
	ErrorCodeRepositoryUnavailable ErrorCode = "repository_unavailable"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeAccessDenied:
		return true
	case ErrorCodeGithubUnavailable:
		return true
	case ErrorCodeInternalError:
		return true
	case ErrorCodeInvalidRequest:
		return true
	case ErrorCodeMethodNotAllowed:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeRateLimited:
		return true
	case ErrorCodeRepositoryUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for IssueAssignmentIssueState.
const (
	Closed IssueAssignmentIssueState = "closed"
	Open   IssueAssignmentIssueState = "open"
)

// Valid indicates whether the value is a known member of the IssueAssignmentIssueState enum.
func (e IssueAssignmentIssueState) Valid() bool {
	switch e {
	case Closed:
		return true
	case Open:
		return true
	default:
		return false
	}
}

// Defines values for ProfileDraftContextSources.
const (
	Checks        ProfileDraftContextSources = "checks"
	Instructions  ProfileDraftContextSources = "instructions"
	Issue         ProfileDraftContextSources = "issue"
	IssueComments ProfileDraftContextSources = "issue_comments"
	PullRequest   ProfileDraftContextSources = "pull_request"
	Repository    ProfileDraftContextSources = "repository"
	ReviewThread  ProfileDraftContextSources = "review_thread"
)

// Valid indicates whether the value is a known member of the ProfileDraftContextSources enum.
func (e ProfileDraftContextSources) Valid() bool {
	switch e {
	case Checks:
		return true
	case Instructions:
		return true
	case Issue:
		return true
	case IssueComments:
		return true
	case PullRequest:
		return true
	case Repository:
		return true
	case ReviewThread:
		return true
	default:
		return false
	}
}

// AssignmentCheck defines model for AssignmentCheck.
type AssignmentCheck struct {
	Conclusion string `json:"conclusion"`
	Status     string `json:"status"`
	Summary    string `json:"summary"`
	Url        string `json:"url"`
}

// AssignmentProposal defines model for AssignmentProposal.
type AssignmentProposal struct {
	Branch    string           `json:"branch"`
	BranchUrl string           `json:"branch_url"`
	Check     *AssignmentCheck `json:"check"`
	Draft     bool             `json:"draft"`
	HeadSha   string           `json:"head_sha"`
	Number    int64            `json:"number"`
	State     string           `json:"state"`
	Url       string           `json:"url"`
}

// AssignmentRequest defines model for AssignmentRequest.
type AssignmentRequest struct {
	CommentId       int64                  `json:"comment_id"`
	CreatedAt       time.Time              `json:"created_at"`
	Edited          bool                   `json:"edited"`
	ProfileRevision string                 `json:"profile_revision"`
	Proposal        *AssignmentProposal    `json:"proposal"`
	Requester       string                 `json:"requester"`
	RequesterId     int64                  `json:"requester_id"`
	Run             *AssignmentRun         `json:"run"`
	State           AssignmentRequestState `json:"state"`
	Summary         string                 `json:"summary"`
	Url             string                 `json:"url"`
}

// AssignmentRequestState defines model for AssignmentRequest.State.
type AssignmentRequestState string

// AssignmentRun defines model for AssignmentRun.
type AssignmentRun struct {
	Attempt    int64  `json:"attempt"`
	Conclusion string `json:"conclusion"`
	Id         int64  `json:"id"`
	Status     string `json:"status"`
	Url        string `json:"url"`
}

// BootstrapDiagnostic defines model for BootstrapDiagnostic.
type BootstrapDiagnostic struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	Path    string `json:"path"`
}

// BootstrapPreview defines model for BootstrapPreview.
type BootstrapPreview struct {
	BaseRevision  string                 `json:"base_revision"`
	DefaultBranch string                 `json:"default_branch"`
	Diagnostics   []BootstrapDiagnostic  `json:"diagnostics"`
	Diff          string                 `json:"diff"`
	Digest        string                 `json:"digest"`
	Files         []BootstrapPreviewFile `json:"files"`
	Private       bool                   `json:"private"`
	Repository    string                 `json:"repository"`
	State         BootstrapPreviewState  `json:"state"`
}

// BootstrapPreviewState defines model for BootstrapPreview.State.
type BootstrapPreviewState string

// BootstrapPreviewFile defines model for BootstrapPreviewFile.
type BootstrapPreviewFile struct {
	BaseSha *string                    `json:"base_sha"`
	Content string                     `json:"content"`
	Path    string                     `json:"path"`
	Sha256  *string                    `json:"sha256"`
	Status  BootstrapPreviewFileStatus `json:"status"`
}

// BootstrapPreviewFileStatus defines model for BootstrapPreviewFile.Status.
type BootstrapPreviewFileStatus string

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for Error.Code.
type ErrorCode string

// IssueAssignment defines model for IssueAssignment.
type IssueAssignment struct {
	Assignable      bool                      `json:"assignable"`
	Body            string                    `json:"body"`
	Command         string                    `json:"command"`
	IssueState      IssueAssignmentIssueState `json:"issue_state"`
	LastCommentId   int64                     `json:"last_comment_id"`
	Number          int64                     `json:"number"`
	ProfileRevision string                    `json:"profile_revision"`
	Reason          string                    `json:"reason"`
	Repository      string                    `json:"repository"`
	RepositoryId    int64                     `json:"repository_id"`
	Requests        []AssignmentRequest       `json:"requests"`
	Title           string                    `json:"title"`
	Url             string                    `json:"url"`
}

// IssueAssignmentIssueState defines model for IssueAssignment.IssueState.
type IssueAssignmentIssueState string

// ProfileDraft defines model for ProfileDraft.
type ProfileDraft struct {
	ContextSources []ProfileDraftContextSources `json:"context_sources"`
	Description    string                       `json:"description"`
	Enabled        bool                         `json:"enabled"`
	Name           string                       `json:"name"`
	ReviewComments bool                         `json:"review_comments"`
}

// ProfileDraftContextSources defines model for ProfileDraft.ContextSources.
type ProfileDraftContextSources string

// InternalError defines model for InternalError.
type InternalError = Error

// MethodNotAllowed defines model for MethodNotAllowed.
type MethodNotAllowed = Error

// PreviewRepositoryProfileJSONRequestBody defines body for PreviewRepositoryProfile for application/json ContentType.
type PreviewRepositoryProfileJSONRequestBody = ProfileDraft
