/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Check process liveness
		 * @description Liveness does not verify GitHub access, configuration, or a runner.
		 */
		get: operations['getHealth'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		/** Check liveness without a response body */
		head: operations['headHealth'];
		patch?: never;
		trace?: never;
	};
	'/v1/assignment-convention': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Read the supported GitHub assignment convention
		 * @description Static protocol metadata for AW-002/AW-003, independent of repository state. This response does not authorize an actor or submit an assignment.
		 */
		get: operations['getAssignmentConvention'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		/** Check convention availability without a response body */
		head: operations['headAssignmentConvention'];
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		Health: {
			/** @enum {string} */
			status: 'ok';
		};
		AssignmentConvention: {
			/** @enum {integer} */
			version: 1;
			/** @enum {string} */
			profile_catalog_path: '.github/agent-profiles.yml';
			/** @enum {integer} */
			profile_schema_version: 1;
			assignment: components['schemas']['AssignmentPolicy'];
		};
		AssignmentPolicy: {
			/** @enum {string} */
			event: 'issue_comment.created';
			/** @enum {string} */
			source_kind: 'issue';
			/** @enum {string} */
			command_template: '/agent assign {profile_id}@{profile_revision} authority=branch-draft-pr';
			/** @enum {string} */
			authority: 'branch-draft-pr';
			required_roles: ('maintain' | 'admin')[];
			profile_revision: components['schemas']['ProfileRevisionPolicy'];
		};
		ProfileRevisionPolicy: {
			/** @enum {string} */
			format: 'full-40-character-sha';
			/** @enum {boolean} */
			default_branch_ancestor: true;
		};
		Error: {
			/** @enum {string} */
			code: 'internal_error' | 'method_not_allowed' | 'not_found';
			message: string;
		};
	};
	responses: {
		/** @description This endpoint accepts only GET and HEAD. */
		MethodNotAllowed: {
			headers: {
				Allow?: 'GET, HEAD';
				[name: string]: unknown;
			};
			content: {
				'application/json': components['schemas']['Error'];
			};
		};
		/** @description The convention request could not be completed; retry the service. */
		InternalError: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/json': components['schemas']['Error'];
			};
		};
	};
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	getHealth: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Service process is running. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Health'];
				};
			};
			405: components['responses']['MethodNotAllowed'];
		};
	};
	headHealth: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Service process is running. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	getAssignmentConvention: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Supported convention and profile catalog version. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AssignmentConvention'];
				};
			};
			405: components['responses']['MethodNotAllowed'];
			500: components['responses']['InternalError'];
		};
	};
	headAssignmentConvention: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Supported convention is available. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description The convention request could not be completed; retry the service. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
}
type ReadonlyArray<T> = [Exclude<T, undefined>] extends [unknown[]]
	? Readonly<Exclude<T, undefined>>
	: Readonly<Exclude<T, undefined>[]>;
export const healthStatusValues: ReadonlyArray<components['schemas']['Health']['status']> = ['ok'];
export const assignmentConventionVersionValues: ReadonlyArray<
	components['schemas']['AssignmentConvention']['version']
> = [1];
export const assignmentConventionProfile_catalog_pathValues: ReadonlyArray<
	components['schemas']['AssignmentConvention']['profile_catalog_path']
> = ['.github/agent-profiles.yml'];
export const assignmentConventionProfile_schema_versionValues: ReadonlyArray<
	components['schemas']['AssignmentConvention']['profile_schema_version']
> = [1];
export const assignmentPolicyEventValues: ReadonlyArray<
	components['schemas']['AssignmentPolicy']['event']
> = ['issue_comment.created'];
export const assignmentPolicySource_kindValues: ReadonlyArray<
	components['schemas']['AssignmentPolicy']['source_kind']
> = ['issue'];
export const assignmentPolicyCommand_templateValues: ReadonlyArray<
	components['schemas']['AssignmentPolicy']['command_template']
> = ['/agent assign {profile_id}@{profile_revision} authority=branch-draft-pr'];
export const assignmentPolicyAuthorityValues: ReadonlyArray<
	components['schemas']['AssignmentPolicy']['authority']
> = ['branch-draft-pr'];
export const assignmentPolicyRequired_rolesValues: ReadonlyArray<
	components['schemas']['AssignmentPolicy']['required_roles']
> = ['maintain', 'admin'];
export const profileRevisionPolicyFormatValues: ReadonlyArray<
	components['schemas']['ProfileRevisionPolicy']['format']
> = ['full-40-character-sha'];
export const errorCodeValues: ReadonlyArray<components['schemas']['Error']['code']> = [
	'internal_error',
	'method_not_allowed',
	'not_found'
];
export const componentsResponsesMethodNotAllowedHeadersAllowValues: ReadonlyArray<
	components['responses']['MethodNotAllowed']['headers']['Allow']
> = ['GET, HEAD'];
