/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Check process liveness
		 * @description Liveness does not verify GitHub access, configuration, or a runner.
		 */
		get: operations['getHealth'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		/** Check liveness without a response body */
		head: operations['headHealth'];
		patch?: never;
		trace?: never;
	};
	'/v1/assignment-convention': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Read the supported GitHub assignment convention
		 * @description Static protocol metadata for AW-002/AW-003, independent of repository state. This response does not authorize an actor or submit an assignment.
		 */
		get: operations['getAssignmentConvention'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		/** Check convention availability without a response body */
		head: operations['headAssignmentConvention'];
		patch?: never;
		trace?: never;
	};
	'/v1/repositories/{owner}/{repo}/profiles': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				owner: string;
				repo: string;
			};
			cookie?: never;
		};
		/**
		 * Read profiles at the current default-branch commit
		 * @description Reads GitHub on every request. Missing, malformed, and unsupported catalogs return explicit validation states with no partial profiles. revision is a full Git commit SHA, not the file blob SHA. This service has no durable catalog storage. Caller access is restricted to the private local application network; the configured server-side token determines repository visibility.
		 */
		get: operations['getRepositoryProfiles'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		/** Check profile read availability without a response body */
		head: operations['headRepositoryProfiles'];
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		Health: {
			/** @enum {string} */
			status: 'ok';
		};
		AssignmentConvention: {
			/** @enum {integer} */
			version: 1;
			/** @enum {string} */
			profile_catalog_path: '.github/agent-profiles.yml';
			/** @enum {integer} */
			profile_schema_version: 1;
			assignment: components['schemas']['AssignmentPolicy'];
		};
		AssignmentPolicy: {
			/** @enum {string} */
			event: 'issue_comment.created';
			/** @enum {string} */
			source_kind: 'issue';
			/** @enum {string} */
			command_template: '/agent assign {profile_id}@{profile_revision} authority=branch-draft-pr';
			/** @enum {string} */
			authority: 'branch-draft-pr';
			required_roles: ('maintain' | 'admin')[];
			profile_revision: components['schemas']['ProfileRevisionPolicy'];
		};
		ProfileRevisionPolicy: {
			/** @enum {string} */
			format: 'full-40-character-sha';
			/** @enum {boolean} */
			default_branch_ancestor: true;
		};
		Error: {
			/** @enum {string} */
			code:
				| 'internal_error'
				| 'method_not_allowed'
				| 'not_found'
				| 'invalid_request'
				| 'access_denied'
				| 'repository_unavailable'
				| 'rate_limited'
				| 'github_unavailable';
			message: string;
		};
		RepositoryProfiles: {
			repository: string;
			/** @enum {string} */
			catalog_path: '.github/agent-profiles.yml';
			default_branch: string;
			revision: string;
			/** @enum {string} */
			state: 'valid' | 'missing' | 'invalid' | 'unsupported';
			profiles: components['schemas']['RepositoryProfile'][];
			diagnostics: components['schemas']['ProfileDiagnostic'][];
		};
		RepositoryProfile: {
			id: string;
			revision: string;
			configuration: components['schemas']['CatalogProfile'];
		};
		ProfileDiagnostic: {
			/** @enum {string} */
			code:
				| 'MISSING_FILE'
				| 'INVALID_FILE'
				| 'INVALID_YAML'
				| 'DUPLICATE_KEY'
				| 'UNSUPPORTED_VERSION'
				| 'MISSING_FIELD'
				| 'UNSUPPORTED_FIELD'
				| 'UNSUPPORTED_VALUE'
				| 'INVALID_TYPE'
				| 'INVALID_FORMAT'
				| 'DUPLICATE_VALUE'
				| 'MISSING_CONTEXT'
				| 'LIMIT_EXCEEDED';
			path: string;
			message: string;
		};
		CatalogProfile: {
			enabled: boolean;
			name: string;
			description: string;
			/** @enum {string} */
			role: 'implementation';
			adapter: components['schemas']['CatalogAdapter'];
			model: components['schemas']['CatalogModel'];
			triggers: {
				/** @enum {string} */
				assignment: 'issue_comment.created';
			};
			context: {
				sources: (
					| 'issue'
					| 'issue_comments'
					| 'repository'
					| 'instructions'
					| 'pull_request'
					| 'review_thread'
					| 'checks'
				)[];
				/** @enum {boolean} */
				images: false;
			};
			authority: {
				/** @enum {string} */
				mode: 'branch-draft-pr';
				/** @enum {string} */
				sandbox: 'workspace-write';
				/** @enum {boolean} */
				network: false;
			};
			validation: {
				checks: 'repository-check'[];
				/** @enum {string} */
				on_failure: 'draft-with-evidence';
			};
			continuation: {
				review_comments: boolean;
				/** @enum {string} */
				pipeline: 'disabled';
			};
		};
		CatalogAdapter: {
			/** @enum {string} */
			id: 'codex-chatgpt-private-runner';
			/** @enum {integer} */
			contract_version: 1;
			runner_label: string;
		};
		CatalogModel: {
			id: string;
			/** @enum {string} */
			reasoning_effort: 'low' | 'medium' | 'high' | 'xhigh' | 'max';
			/** @enum {string} */
			fallback: 'none';
		};
	};
	responses: {
		/** @description This endpoint accepts only GET and HEAD. */
		MethodNotAllowed: {
			headers: {
				Allow?: 'GET, HEAD';
				[name: string]: unknown;
			};
			content: {
				'application/json': components['schemas']['Error'];
			};
		};
		/** @description The convention request could not be completed; retry the service. */
		InternalError: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/json': components['schemas']['Error'];
			};
		};
	};
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	getHealth: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Service process is running. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Health'];
				};
			};
			405: components['responses']['MethodNotAllowed'];
		};
	};
	headHealth: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Service process is running. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	getAssignmentConvention: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Supported convention and profile catalog version. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AssignmentConvention'];
				};
			};
			405: components['responses']['MethodNotAllowed'];
			500: components['responses']['InternalError'];
		};
	};
	headAssignmentConvention: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Supported convention is available. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description The convention request could not be completed; retry the service. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	getRepositoryProfiles: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				owner: string;
				repo: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Fresh repository catalog projection and validation results. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['RepositoryProfiles'];
				};
			};
			/** @description Invalid owner or repository name. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Read credentials lack repository Contents permission. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Repository is unavailable or not visible to the read credentials. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			405: components['responses']['MethodNotAllowed'];
			/** @description GitHub rate limit reached; retry later. */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Service failed; retry. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description GitHub failed or returned an invalid response; retry. */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	headRepositoryProfiles: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				owner: string;
				repo: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Fresh repository catalog projection and validation results. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid owner or repository name. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Read credentials lack repository Contents permission. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Repository is unavailable or not visible to the read credentials. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description This endpoint accepts GET and HEAD. */
			405: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description GitHub rate limit reached; retry later. */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Service failed; retry. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description GitHub failed or returned an invalid response; retry. */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
}
type ReadonlyArray<T> = [Exclude<T, undefined>] extends [unknown[]]
	? Readonly<Exclude<T, undefined>>
	: Readonly<Exclude<T, undefined>[]>;
export const healthStatusValues: ReadonlyArray<components['schemas']['Health']['status']> = ['ok'];
export const assignmentConventionVersionValues: ReadonlyArray<
	components['schemas']['AssignmentConvention']['version']
> = [1];
export const assignmentConventionProfile_catalog_pathValues: ReadonlyArray<
	components['schemas']['AssignmentConvention']['profile_catalog_path']
> = ['.github/agent-profiles.yml'];
export const assignmentConventionProfile_schema_versionValues: ReadonlyArray<
	components['schemas']['AssignmentConvention']['profile_schema_version']
> = [1];
export const assignmentPolicyEventValues: ReadonlyArray<
	components['schemas']['AssignmentPolicy']['event']
> = ['issue_comment.created'];
export const assignmentPolicySource_kindValues: ReadonlyArray<
	components['schemas']['AssignmentPolicy']['source_kind']
> = ['issue'];
export const assignmentPolicyCommand_templateValues: ReadonlyArray<
	components['schemas']['AssignmentPolicy']['command_template']
> = ['/agent assign {profile_id}@{profile_revision} authority=branch-draft-pr'];
export const assignmentPolicyAuthorityValues: ReadonlyArray<
	components['schemas']['AssignmentPolicy']['authority']
> = ['branch-draft-pr'];
export const assignmentPolicyRequired_rolesValues: ReadonlyArray<
	components['schemas']['AssignmentPolicy']['required_roles']
> = ['maintain', 'admin'];
export const profileRevisionPolicyFormatValues: ReadonlyArray<
	components['schemas']['ProfileRevisionPolicy']['format']
> = ['full-40-character-sha'];
export const errorCodeValues: ReadonlyArray<components['schemas']['Error']['code']> = [
	'internal_error',
	'method_not_allowed',
	'not_found',
	'invalid_request',
	'access_denied',
	'repository_unavailable',
	'rate_limited',
	'github_unavailable'
];
export const repositoryProfilesCatalog_pathValues: ReadonlyArray<
	components['schemas']['RepositoryProfiles']['catalog_path']
> = ['.github/agent-profiles.yml'];
export const repositoryProfilesStateValues: ReadonlyArray<
	components['schemas']['RepositoryProfiles']['state']
> = ['valid', 'missing', 'invalid', 'unsupported'];
export const profileDiagnosticCodeValues: ReadonlyArray<
	components['schemas']['ProfileDiagnostic']['code']
> = [
	'MISSING_FILE',
	'INVALID_FILE',
	'INVALID_YAML',
	'DUPLICATE_KEY',
	'UNSUPPORTED_VERSION',
	'MISSING_FIELD',
	'UNSUPPORTED_FIELD',
	'UNSUPPORTED_VALUE',
	'INVALID_TYPE',
	'INVALID_FORMAT',
	'DUPLICATE_VALUE',
	'MISSING_CONTEXT',
	'LIMIT_EXCEEDED'
];
export const catalogProfileRoleValues: ReadonlyArray<
	components['schemas']['CatalogProfile']['role']
> = ['implementation'];
export const catalogProfileTriggersAssignmentValues: ReadonlyArray<
	components['schemas']['CatalogProfile']['triggers']['assignment']
> = ['issue_comment.created'];
export const catalogProfileContextSourcesValues: ReadonlyArray<
	components['schemas']['CatalogProfile']['context']['sources']
> = [
	'issue',
	'issue_comments',
	'repository',
	'instructions',
	'pull_request',
	'review_thread',
	'checks'
];
export const catalogProfileAuthorityModeValues: ReadonlyArray<
	components['schemas']['CatalogProfile']['authority']['mode']
> = ['branch-draft-pr'];
export const catalogProfileAuthoritySandboxValues: ReadonlyArray<
	components['schemas']['CatalogProfile']['authority']['sandbox']
> = ['workspace-write'];
export const catalogProfileValidationChecksValues: ReadonlyArray<
	components['schemas']['CatalogProfile']['validation']['checks']
> = ['repository-check'];
export const catalogProfileValidationOn_failureValues: ReadonlyArray<
	components['schemas']['CatalogProfile']['validation']['on_failure']
> = ['draft-with-evidence'];
export const catalogProfileContinuationPipelineValues: ReadonlyArray<
	components['schemas']['CatalogProfile']['continuation']['pipeline']
> = ['disabled'];
export const catalogAdapterIdValues: ReadonlyArray<components['schemas']['CatalogAdapter']['id']> =
	['codex-chatgpt-private-runner'];
export const catalogAdapterContract_versionValues: ReadonlyArray<
	components['schemas']['CatalogAdapter']['contract_version']
> = [1];
export const catalogModelReasoning_effortValues: ReadonlyArray<
	components['schemas']['CatalogModel']['reasoning_effort']
> = ['low', 'medium', 'high', 'xhigh', 'max'];
export const catalogModelFallbackValues: ReadonlyArray<
	components['schemas']['CatalogModel']['fallback']
> = ['none'];
export const componentsResponsesMethodNotAllowedHeadersAllowValues: ReadonlyArray<
	components['responses']['MethodNotAllowed']['headers']['Allow']
> = ['GET, HEAD'];
