/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Check process liveness
		 * @description Liveness does not verify GitHub access, configuration, or a runner.
		 */
		get: operations['getHealth'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		/** Check liveness without a response body */
		head: operations['headHealth'];
		patch?: never;
		trace?: never;
	};
	'/v1/assignment-convention': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Read the supported GitHub assignment convention
		 * @description Static protocol metadata for AW-002/AW-003, independent of repository state. This response does not authorize an actor or submit an assignment.
		 */
		get: operations['getAssignmentConvention'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		/** Check convention availability without a response body */
		head: operations['headAssignmentConvention'];
		patch?: never;
		trace?: never;
	};
	'/v1/repositories/{owner}/{repo}/profiles': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				owner: string;
				repo: string;
			};
			cookie?: never;
		};
		/**
		 * Read profiles at the current default-branch commit
		 * @description Reads GitHub on every request. Missing, malformed, and unsupported catalogs return explicit validation states with no partial profiles. revision is a full Git commit SHA, not the file blob SHA. This service has no durable catalog storage. Caller access is restricted to the private local application network; the configured server-side token determines repository visibility.
		 */
		get: operations['getRepositoryProfiles'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		/** Check profile read availability without a response body */
		head: operations['headRepositoryProfiles'];
		patch?: never;
		trace?: never;
	};
	'/v1/repositories/{owner}/{repo}/readiness': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				owner: string;
				repo: string;
			};
			cookie?: never;
		};
		/**
		 * Derive repository profile readiness
		 * @description Fresh commit-pinned configuration and latest diagnostic attempt. Evidence must match the repository, revision, exact model policy, dedicated runner, and trusted GitHub jobs, and be at most 24 hours old. Missing bootstrap files differ from pending or failed verification. Read credentials require Metadata, Contents, and Actions read permissions. Service remains private to the local application network.
		 */
		get: operations['getRepositoryReadiness'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		/** Check readiness read availability without a response body */
		head: operations['headRepositoryReadiness'];
		patch?: never;
		trace?: never;
	};
	'/v1/repositories/{owner}/{repo}/bootstrap': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				owner: string;
				repo: string;
			};
			cookie?: never;
		};
		/**
		 * Review the canonical codex-thorough bootstrap changes
		 * @description Fresh commit-pinned file plan and applicable diff. No GitHub writes, runner provisioning, credentials, persisted draft, or authorization grant. The digest binds the target base and every proposed file. Private network only.
		 */
		get: operations['getRepositoryBootstrap'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		/** Check bootstrap preview availability without returning source */
		head: operations['headRepositoryBootstrap'];
		patch?: never;
		trace?: never;
	};
	'/v1/repositories/{owner}/{repo}/profile-editor': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				owner: string;
				repo: string;
			};
			cookie?: never;
		};
		/**
		 * Read editable codex-thorough choices from the current repository
		 * @description Private-network authoring context. No persistence, credentials or write authorization.
		 */
		get: operations['getRepositoryProfileEditor'];
		put?: never;
		/**
		 * Generate a fresh profile configuration and bootstrap review
		 * @description Accepts only structured choices. Canonical schema validation and fixed adapter policy apply. Existing unrelated profiles are preserved. No GitHub writes or durable draft.
		 */
		post: operations['previewRepositoryProfile'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/repositories/{owner}/{repo}/issues/{number}/assignment': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				owner: string;
				repo: string;
				number: number;
			};
			cookie?: never;
		};
		/**
		 * Read issue assignment context and GitHub-derived outcomes
		 * @description Fresh read-only projection. No runner access or durable run state. Links and check outcomes are corroborated with GitHub workflow, request, ref and PR objects; never authorization. Incomplete evidence remains explicit.
		 */
		get: operations['getIssueAssignment'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}

export type webhooks = Record<string, never>;

export interface components {
	schemas: {
		ProfileEditor: {
			base_revision: string;
			draft: components['schemas']['ProfileDraft'] | null;
			diagnostics: components['schemas']['BootstrapDiagnostic'][];
		};
		BootstrapPreview: {
			repository: string;
			default_branch: string;
			base_revision: string;
			digest: string;
			/** @enum {string} */
			state: 'ready' | 'unchanged' | 'conflict';
			private: boolean;
			files: components['schemas']['BootstrapPreviewFile'][];
			diagnostics: components['schemas']['BootstrapDiagnostic'][];
			diff: string;
		};
		BootstrapDiagnostic: {
			code: string;
			path: string;
			message: string;
		};
		BootstrapPreviewFile: {
			path: string;
			/** @enum {string} */
			status: 'create' | 'update' | 'unchanged' | 'conflict';
			base_sha: string | null;
			sha256: string | null;
			content: string;
		};
		Health: {
			/** @enum {string} */
			status: 'ok';
		};
		AssignmentConvention: {
			/** @enum {integer} */
			version: 1;
			/** @enum {string} */
			profile_catalog_path: '.github/agent-profiles.yml';
			/** @enum {integer} */
			profile_schema_version: 1;
			assignment: components['schemas']['AssignmentPolicy'];
		};
		AssignmentPolicy: {
			/** @enum {string} */
			event: 'issue_comment.created';
			/** @enum {string} */
			source_kind: 'issue';
			/** @enum {string} */
			command_template: '/agent assign {profile_id}@{profile_revision} authority=branch-draft-pr';
			/** @enum {string} */
			authority: 'branch-draft-pr';
			required_roles: ('maintain' | 'admin')[];
			profile_revision: components['schemas']['ProfileRevisionPolicy'];
		};
		ProfileRevisionPolicy: {
			/** @enum {string} */
			format: 'full-40-character-sha';
			/** @enum {boolean} */
			default_branch_ancestor: true;
		};
		Error: {
			/** @enum {string} */
			code:
				| 'internal_error'
				| 'method_not_allowed'
				| 'not_found'
				| 'invalid_request'
				| 'access_denied'
				| 'repository_unavailable'
				| 'rate_limited'
				| 'github_unavailable';
			message: string;
		};
		RepositoryProfiles: {
			repository: string;
			/** @enum {string} */
			catalog_path: '.github/agent-profiles.yml';
			default_branch: string;
			revision: string;
			/** @enum {string} */
			state: 'valid' | 'missing' | 'invalid' | 'unsupported';
			profiles: components['schemas']['RepositoryProfile'][];
			diagnostics: components['schemas']['ProfileDiagnostic'][];
		};
		RepositoryProfile: {
			id: string;
			revision: string;
			configuration: components['schemas']['CatalogProfile'];
		};
		ProfileDiagnostic: {
			/** @enum {string} */
			code:
				| 'MISSING_FILE'
				| 'INVALID_FILE'
				| 'INVALID_YAML'
				| 'DUPLICATE_KEY'
				| 'UNSUPPORTED_VERSION'
				| 'MISSING_FIELD'
				| 'UNSUPPORTED_FIELD'
				| 'UNSUPPORTED_VALUE'
				| 'INVALID_TYPE'
				| 'INVALID_FORMAT'
				| 'DUPLICATE_VALUE'
				| 'MISSING_CONTEXT'
				| 'LIMIT_EXCEEDED';
			path: string;
			message: string;
		};
		ReadinessDiagnostic: {
			/** @enum {string} */
			code:
				| 'MISSING_FILE'
				| 'WORKFLOW_CONFIGURATION'
				| 'EVIDENCE_MISSING'
				| 'EVIDENCE_ORIGIN'
				| 'EVIDENCE_POLICY'
				| 'EVIDENCE_STALE'
				| 'RUNTIME_FAILED';
			path: string;
			message: string;
		};
		ProfileReadiness: {
			id: string;
			revision: string;
			/** @enum {string} */
			state:
				| 'configuration_missing'
				| 'verification_pending'
				| 'runtime_verified'
				| 'verification_failed';
			runner_label: string;
			next_action: string;
			diagnostics: components['schemas']['ReadinessDiagnostic'][];
			evidence?: components['schemas']['RuntimeEvidence'];
		};
		RepositoryReadiness: {
			repository: string;
			default_branch: string;
			revision: string;
			/** @enum {string} */
			catalog_state: 'valid' | 'missing' | 'invalid' | 'unsupported';
			profiles: components['schemas']['ProfileReadiness'][];
			diagnostics: components['schemas']['ProfileDiagnostic'][];
		};
		AssignmentCheck: {
			/** Format: uri */
			url: string;
			status: string;
			conclusion: string;
			summary: string;
		};
		AssignmentProposal: {
			/** Format: int64 */
			number: number;
			/** Format: uri */
			url: string;
			state: string;
			draft: boolean;
			branch: string;
			/** Format: uri */
			branch_url: string;
			head_sha: string;
			check: components['schemas']['AssignmentCheck'] | null;
		};
		AssignmentRun: {
			/** Format: int64 */
			id: number;
			/** Format: int64 */
			attempt: number;
			/** Format: uri */
			url: string;
			status: string;
			conclusion: string;
		};
		AssignmentRequest: {
			/** Format: int64 */
			comment_id: number;
			/** Format: uri */
			url: string;
			/** Format: int64 */
			requester_id: number;
			requester: string;
			profile_revision: string;
			/** Format: date-time */
			created_at: string;
			edited: boolean;
			/** @enum {string} */
			state:
				| 'requested'
				| 'queued'
				| 'running'
				| 'blocked'
				| 'failed'
				| 'cancelled'
				| 'completed'
				| 'proposal'
				| 'unavailable';
			run: components['schemas']['AssignmentRun'] | null;
			proposal: components['schemas']['AssignmentProposal'] | null;
			summary: string;
		};
		IssueAssignment: {
			repository: string;
			/** Format: int64 */
			repository_id: number;
			/** Format: int64 */
			number: number;
			title: string;
			body: string;
			/** Format: uri */
			url: string;
			/** @enum {string} */
			issue_state: 'open' | 'closed';
			profile_revision: string;
			assignable: boolean;
			reason: string;
			command: string;
			/** Format: int64 */
			last_comment_id: number;
			requests: components['schemas']['AssignmentRequest'][];
		};
		CatalogProfile: {
			enabled: boolean;
			name: string;
			description: string;
			/** @enum {string} */
			role: 'implementation';
			adapter: components['schemas']['CatalogAdapter'];
			model: components['schemas']['CatalogModel'];
			triggers: {
				/** @enum {string} */
				assignment: 'issue_comment.created';
			};
			context: {
				sources: (
					| 'issue'
					| 'issue_comments'
					| 'repository'
					| 'instructions'
					| 'pull_request'
					| 'review_thread'
					| 'checks'
				)[];
				/** @enum {boolean} */
				images: false;
			};
			authority: {
				/** @enum {string} */
				mode: 'branch-draft-pr';
				/** @enum {string} */
				sandbox: 'workspace-write';
				/** @enum {boolean} */
				network: false;
			};
			validation: {
				checks: 'repository-check'[];
				/** @enum {string} */
				on_failure: 'draft-with-evidence';
			};
			continuation: {
				review_comments: boolean;
				/** @enum {string} */
				pipeline: 'disabled';
			};
		};
		CatalogAdapter: {
			/** @enum {string} */
			id: 'codex-chatgpt-private-runner';
			/** @enum {integer} */
			contract_version: 1;
			runner_label: string;
		};
		CatalogModel: {
			id: string;
			/** @enum {string} */
			reasoning_effort: 'low' | 'medium' | 'high' | 'xhigh' | 'max';
			/** @enum {string} */
			fallback: 'none';
		};
		ProfileDraft: {
			name: string;
			description: string;
			enabled: boolean;
			context_sources: (
				| 'issue'
				| 'issue_comments'
				| 'repository'
				| 'instructions'
				| 'pull_request'
				| 'review_thread'
				| 'checks'
			)[];
			review_comments: boolean;
		};
		RuntimeEvidence: {
			/** @enum {integer} */
			version: 1;
			repository: string;
			profile_id: string;
			profile_revision: string;
			runner_label: string;
			/** @enum {string} */
			requested_model: 'gpt-6.1-sol';
			/** @enum {string} */
			requested_reasoning_effort: 'high';
			/** @enum {string|null} */
			effective_model: 'gpt-6.1-sol' | null;
			/** @enum {string|null} */
			effective_reasoning_effort: 'high' | null;
			cli_version: string | null;
			run_id: number;
			run_attempt: number;
			/** Format: date-time */
			verified_at: string;
			/** @enum {string} */
			outcome: 'verified' | 'failed';
			/** @enum {string} */
			reason_code:
				| 'verified'
				| 'installation_unavailable'
				| 'authentication_unavailable'
				| 'request_failed'
				| 'effective_policy_unavailable';
		};
	};
	responses: {
		/** @description This endpoint accepts only GET and HEAD. */
		MethodNotAllowed: {
			headers: {
				Allow?: 'GET, HEAD';
				[name: string]: unknown;
			};
			content: {
				'application/json': components['schemas']['Error'];
			};
		};
		/** @description The convention request could not be completed; retry the service. */
		InternalError: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/json': components['schemas']['Error'];
			};
		};
	};
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}

export type $defs = Record<string, never>;

export interface operations {
	getHealth: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Service process is running. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Health'];
				};
			};
			405: components['responses']['MethodNotAllowed'];
		};
	};
	headHealth: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Service process is running. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	getAssignmentConvention: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Supported convention and profile catalog version. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AssignmentConvention'];
				};
			};
			405: components['responses']['MethodNotAllowed'];
			500: components['responses']['InternalError'];
		};
	};
	headAssignmentConvention: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Supported convention is available. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description The convention request could not be completed; retry the service. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	getRepositoryProfiles: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				owner: string;
				repo: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Fresh repository catalog projection and validation results. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['RepositoryProfiles'];
				};
			};
			/** @description Invalid owner or repository name. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Read credentials lack repository Contents permission. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Repository is unavailable or not visible to the read credentials. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			405: components['responses']['MethodNotAllowed'];
			/** @description GitHub rate limit reached; retry later. */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Service failed; retry. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description GitHub failed or returned an invalid response; retry. */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	headRepositoryProfiles: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				owner: string;
				repo: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Fresh repository catalog projection and validation results. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid owner or repository name. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Read credentials lack repository Contents permission. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Repository is unavailable or not visible to the read credentials. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description This endpoint accepts GET and HEAD. */
			405: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description GitHub rate limit reached; retry later. */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Service failed; retry. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description GitHub failed or returned an invalid response; retry. */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	getRepositoryReadiness: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				owner: string;
				repo: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Configuration and runtime readiness for each validated profile. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['RepositoryReadiness'];
				};
			};
			/** @description Invalid owner or repository name. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Read credentials lack Metadata, Contents, or Actions read access. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Repository is unavailable or not visible to the read credentials. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			405: components['responses']['MethodNotAllowed'];
			/** @description GitHub rate limit reached; retry later. */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Service failed; retry. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description GitHub failed or returned an invalid response; retry. */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	headRepositoryReadiness: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				owner: string;
				repo: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Fresh repository catalog projection and validation results. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid owner or repository name. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Read credentials lack repository Contents permission. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Repository is unavailable or not visible to the read credentials. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description This endpoint accepts GET and HEAD. */
			405: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description GitHub rate limit reached; retry later. */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Service failed; retry. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description GitHub failed or returned an invalid response; retry. */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	getRepositoryBootstrap: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				owner: string;
				repo: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Reviewable plan; conflicts and unchanged configurations cannot be published. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['BootstrapPreview'];
				};
			};
			/** @description Invalid repository. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Discovery credentials cannot read the repository. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Repository, initialized default branch, or supported regular files unavailable. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			405: components['responses']['MethodNotAllowed'];
			/** @description Rate limited; retry later. */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			500: components['responses']['InternalError'];
			/** @description Canonical templates or complete GitHub snapshot unavailable. */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	headRepositoryBootstrap: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				owner: string;
				repo: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Preview available. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid repository. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Discovery credentials cannot read the repository. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Repository or supported snapshot unavailable. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description This endpoint accepts GET and HEAD. */
			405: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Rate limited. */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Bootstrap planning unavailable. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Complete snapshot or templates unavailable. */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	getRepositoryProfileEditor: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				owner: string;
				repo: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Current choices or actionable policy/catalog conflicts. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ProfileEditor'];
				};
			};
			400: components['responses']['InternalError'];
			403: components['responses']['InternalError'];
			404: components['responses']['InternalError'];
			429: components['responses']['InternalError'];
			502: components['responses']['InternalError'];
		};
	};
	previewRepositoryProfile: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				owner: string;
				repo: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ProfileDraft'];
			};
		};
		responses: {
			/** @description Commit-pinned preview; invalid choices produce conflict diagnostics and cannot publish. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['BootstrapPreview'];
				};
			};
			400: components['responses']['InternalError'];
			403: components['responses']['InternalError'];
			404: components['responses']['InternalError'];
			429: components['responses']['InternalError'];
			502: components['responses']['InternalError'];
		};
	};
	getIssueAssignment: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				owner: string;
				repo: string;
				number: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Issue, current profile and bounded request history. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['IssueAssignment'];
				};
			};
			/** @description Invalid owner or repository name. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Read credentials lack repository Contents permission. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Repository is unavailable or not visible to the read credentials. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			405: components['responses']['MethodNotAllowed'];
			/** @description GitHub rate limit reached; retry later. */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Service failed; retry. */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description GitHub failed or returned an invalid response; retry. */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
}

type ReadonlyArray<T> = [Exclude<T, undefined>] extends [unknown[]]
	? Readonly<Exclude<T, undefined>>
	: Readonly<Exclude<T, undefined>[]>;
export const bootstrapPreviewStateValues: ReadonlyArray<
	components['schemas']['BootstrapPreview']['state']
> = ['ready', 'unchanged', 'conflict'];
export const bootstrapPreviewFileStatusValues: ReadonlyArray<
	components['schemas']['BootstrapPreviewFile']['status']
> = ['create', 'update', 'unchanged', 'conflict'];
export const healthStatusValues: ReadonlyArray<components['schemas']['Health']['status']> = ['ok'];
export const assignmentConventionVersionValues: ReadonlyArray<
	components['schemas']['AssignmentConvention']['version']
> = [1];
export const assignmentConventionProfile_catalog_pathValues: ReadonlyArray<
	components['schemas']['AssignmentConvention']['profile_catalog_path']
> = ['.github/agent-profiles.yml'];
export const assignmentConventionProfile_schema_versionValues: ReadonlyArray<
	components['schemas']['AssignmentConvention']['profile_schema_version']
> = [1];
export const assignmentPolicyEventValues: ReadonlyArray<
	components['schemas']['AssignmentPolicy']['event']
> = ['issue_comment.created'];
export const assignmentPolicySource_kindValues: ReadonlyArray<
	components['schemas']['AssignmentPolicy']['source_kind']
> = ['issue'];
export const assignmentPolicyCommand_templateValues: ReadonlyArray<
	components['schemas']['AssignmentPolicy']['command_template']
> = ['/agent assign {profile_id}@{profile_revision} authority=branch-draft-pr'];
export const assignmentPolicyAuthorityValues: ReadonlyArray<
	components['schemas']['AssignmentPolicy']['authority']
> = ['branch-draft-pr'];
export const assignmentPolicyRequired_rolesValues: ReadonlyArray<
	components['schemas']['AssignmentPolicy']['required_roles']
> = ['maintain', 'admin'];
export const profileRevisionPolicyFormatValues: ReadonlyArray<
	components['schemas']['ProfileRevisionPolicy']['format']
> = ['full-40-character-sha'];
export const errorCodeValues: ReadonlyArray<components['schemas']['Error']['code']> = [
	'internal_error',
	'method_not_allowed',
	'not_found',
	'invalid_request',
	'access_denied',
	'repository_unavailable',
	'rate_limited',
	'github_unavailable'
];
export const repositoryProfilesCatalog_pathValues: ReadonlyArray<
	components['schemas']['RepositoryProfiles']['catalog_path']
> = ['.github/agent-profiles.yml'];
export const repositoryProfilesStateValues: ReadonlyArray<
	components['schemas']['RepositoryProfiles']['state']
> = ['valid', 'missing', 'invalid', 'unsupported'];
export const profileDiagnosticCodeValues: ReadonlyArray<
	components['schemas']['ProfileDiagnostic']['code']
> = [
	'MISSING_FILE',
	'INVALID_FILE',
	'INVALID_YAML',
	'DUPLICATE_KEY',
	'UNSUPPORTED_VERSION',
	'MISSING_FIELD',
	'UNSUPPORTED_FIELD',
	'UNSUPPORTED_VALUE',
	'INVALID_TYPE',
	'INVALID_FORMAT',
	'DUPLICATE_VALUE',
	'MISSING_CONTEXT',
	'LIMIT_EXCEEDED'
];
export const readinessDiagnosticCodeValues: ReadonlyArray<
	components['schemas']['ReadinessDiagnostic']['code']
> = [
	'MISSING_FILE',
	'WORKFLOW_CONFIGURATION',
	'EVIDENCE_MISSING',
	'EVIDENCE_ORIGIN',
	'EVIDENCE_POLICY',
	'EVIDENCE_STALE',
	'RUNTIME_FAILED'
];
export const profileReadinessStateValues: ReadonlyArray<
	components['schemas']['ProfileReadiness']['state']
> = ['configuration_missing', 'verification_pending', 'runtime_verified', 'verification_failed'];
export const repositoryReadinessCatalog_stateValues: ReadonlyArray<
	components['schemas']['RepositoryReadiness']['catalog_state']
> = ['valid', 'missing', 'invalid', 'unsupported'];
export const assignmentRequestStateValues: ReadonlyArray<
	components['schemas']['AssignmentRequest']['state']
> = [
	'requested',
	'queued',
	'running',
	'blocked',
	'failed',
	'cancelled',
	'completed',
	'proposal',
	'unavailable'
];
export const issueAssignmentIssue_stateValues: ReadonlyArray<
	components['schemas']['IssueAssignment']['issue_state']
> = ['open', 'closed'];
export const catalogProfileRoleValues: ReadonlyArray<
	components['schemas']['CatalogProfile']['role']
> = ['implementation'];
export const catalogProfileTriggersAssignmentValues: ReadonlyArray<
	components['schemas']['CatalogProfile']['triggers']['assignment']
> = ['issue_comment.created'];
export const catalogProfileContextSourcesValues: ReadonlyArray<
	components['schemas']['CatalogProfile']['context']['sources']
> = [
	'issue',
	'issue_comments',
	'repository',
	'instructions',
	'pull_request',
	'review_thread',
	'checks'
];
export const catalogProfileAuthorityModeValues: ReadonlyArray<
	components['schemas']['CatalogProfile']['authority']['mode']
> = ['branch-draft-pr'];
export const catalogProfileAuthoritySandboxValues: ReadonlyArray<
	components['schemas']['CatalogProfile']['authority']['sandbox']
> = ['workspace-write'];
export const catalogProfileValidationChecksValues: ReadonlyArray<
	components['schemas']['CatalogProfile']['validation']['checks']
> = ['repository-check'];
export const catalogProfileValidationOn_failureValues: ReadonlyArray<
	components['schemas']['CatalogProfile']['validation']['on_failure']
> = ['draft-with-evidence'];
export const catalogProfileContinuationPipelineValues: ReadonlyArray<
	components['schemas']['CatalogProfile']['continuation']['pipeline']
> = ['disabled'];
export const catalogAdapterIdValues: ReadonlyArray<components['schemas']['CatalogAdapter']['id']> =
	['codex-chatgpt-private-runner'];
export const catalogAdapterContract_versionValues: ReadonlyArray<
	components['schemas']['CatalogAdapter']['contract_version']
> = [1];
export const catalogModelReasoning_effortValues: ReadonlyArray<
	components['schemas']['CatalogModel']['reasoning_effort']
> = ['low', 'medium', 'high', 'xhigh', 'max'];
export const catalogModelFallbackValues: ReadonlyArray<
	components['schemas']['CatalogModel']['fallback']
> = ['none'];
export const profileDraftContext_sourcesValues: ReadonlyArray<
	components['schemas']['ProfileDraft']['context_sources']
> = [
	'issue',
	'issue_comments',
	'repository',
	'instructions',
	'pull_request',
	'review_thread',
	'checks'
];
export const runtimeEvidenceVersionValues: ReadonlyArray<
	components['schemas']['RuntimeEvidence']['version']
> = [1];
export const runtimeEvidenceRequested_modelValues: ReadonlyArray<
	components['schemas']['RuntimeEvidence']['requested_model']
> = ['gpt-6.1-sol'];
export const runtimeEvidenceRequested_reasoning_effortValues: ReadonlyArray<
	components['schemas']['RuntimeEvidence']['requested_reasoning_effort']
> = ['high'];
export const runtimeEvidenceEffective_modelValues: ReadonlyArray<
	components['schemas']['RuntimeEvidence']['effective_model']
> = ['gpt-6.1-sol'];
export const runtimeEvidenceEffective_reasoning_effortValues: ReadonlyArray<
	components['schemas']['RuntimeEvidence']['effective_reasoning_effort']
> = ['high'];
export const runtimeEvidenceOutcomeValues: ReadonlyArray<
	components['schemas']['RuntimeEvidence']['outcome']
> = ['verified', 'failed'];
export const runtimeEvidenceReason_codeValues: ReadonlyArray<
	components['schemas']['RuntimeEvidence']['reason_code']
> = [
	'verified',
	'installation_unavailable',
	'authentication_unavailable',
	'request_failed',
	'effective_policy_unavailable'
];
export const componentsResponsesMethodNotAllowedHeadersAllowValues: ReadonlyArray<
	components['responses']['MethodNotAllowed']['headers']['Allow']
> = ['GET, HEAD'];
