/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['getHealth'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head: operations['headHealth'];
		patch?: never;
		trace?: never;
	};
	'/v1/session': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description Verify the App-bound user token, refreshing it when necessary. Missing cookies return signed_out; invalid sessions are cleared. */
		get: operations['getSession'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/sign-in': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** @description Exact public Origin required. Sets a ten-minute HttpOnly binding cookie and redirects to GitHub with one-use state and S256 PKCE. Requests no OAuth scopes. */
		post: operations['startSignIn'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/sign-in/callback': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description Requires the browser-binding cookie and one-use state. Exchanges code server-side, verifies App-bound identity, creates a fresh session, and redirects to /account. */
		get: operations['completeSignIn'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/sign-out': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['signOut'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/repositories/{owner}/{repo}/authorization': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** @description Live identity, token, repository, role, installation selection, and App permission checks. Assignment requires maintain/admin and Issues write. Bootstrap requires write/maintain/admin and Contents, Pull requests, and Workflows write. Archived/disabled repositories fail closed. This is preflight context, never a reusable write permit or credential. */
		post: operations['authorizeRepository'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}

export type webhooks = Record<string, never>;

export interface components {
	schemas: {
		Health: {
			/** @enum {string} */
			status: 'ok';
		};
		User: {
			/** Format: int64 */
			id: number;
			login: string;
		};
		Session: {
			/** @enum {string} */
			state: 'disabled' | 'signed_out' | 'authenticated';
			user: components['schemas']['User'] | null;
			csrf: string | null;
			/** Format: date-time */
			expires_at: string | null;
		};
		ProtectedRequest: {
			csrf: string;
		};
		/** @enum {string} */
		Action: 'assign_comment' | 'bootstrap_pull_request';
		AuthorizationRequest: {
			csrf: string;
			action: components['schemas']['Action'];
		};
		Authorization: {
			user: components['schemas']['User'];
			/** Format: int64 */
			repository_id: number;
			repository: string;
			action: components['schemas']['Action'];
			/** Format: date-time */
			checked_at: string;
		};
		SignOutResult: {
			revoked: boolean;
			message: string;
		};
		Error: {
			/** @enum {string} */
			code:
				| 'invalid_request'
				| 'reconnect_required'
				| 'forbidden'
				| 'forgery_rejected'
				| 'identity_unavailable'
				| 'not_found'
				| 'method_not_allowed';
			message: string;
		};
	};
	responses: {
		/** @description Safe recovery guidance, without provider text or credentials. */
		Error: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/json': components['schemas']['Error'];
			};
		};
	};
	parameters: {
		/** @description Exact configured public origin, required for every POST. */
		Origin: string;
	};
	requestBodies: never;
	headers: never;
	pathItems: never;
}

export type $defs = Record<string, never>;

export interface operations {
	getHealth: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Service is alive, even when sign-in is unconfigured. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Health'];
				};
			};
		};
	};
	headHealth: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Service is alive. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	getSession: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Safe identity status; never credentials. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Session'];
				};
			};
			400: components['responses']['Error'];
			401: components['responses']['Error'];
			403: components['responses']['Error'];
			503: components['responses']['Error'];
		};
	};
	startSignIn: {
		parameters: {
			query?: never;
			header: {
				/** @description Exact configured public origin, required for every POST. */
				Origin: components['parameters']['Origin'];
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Continue authorization; sets an opaque HttpOnly browser cookie. */
			303: {
				headers: {
					Location?: string;
					'Set-Cookie'?: string;
					[name: string]: unknown;
				};
				content?: never;
			};
			400: components['responses']['Error'];
			401: components['responses']['Error'];
			403: components['responses']['Error'];
			503: components['responses']['Error'];
		};
	};
	completeSignIn: {
		parameters: {
			query: {
				state: string;
				code: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Continue authorization; sets an opaque HttpOnly browser cookie. */
			303: {
				headers: {
					Location?: string;
					'Set-Cookie'?: string;
					[name: string]: unknown;
				};
				content?: never;
			};
			400: components['responses']['Error'];
			401: components['responses']['Error'];
			403: components['responses']['Error'];
			503: components['responses']['Error'];
		};
	};
	signOut: {
		parameters: {
			query?: never;
			header: {
				/** @description Exact configured public origin, required for every POST. */
				Origin: components['parameters']['Origin'];
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ProtectedRequest'];
			};
		};
		responses: {
			/** @description Local session removed before remote revocation. Failure includes GitHub settings recovery. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SignOutResult'];
				};
			};
			400: components['responses']['Error'];
			401: components['responses']['Error'];
			403: components['responses']['Error'];
			503: components['responses']['Error'];
		};
	};
	authorizeRepository: {
		parameters: {
			query?: never;
			header: {
				/** @description Exact configured public origin, required for every POST. */
				Origin: components['parameters']['Origin'];
			};
			path: {
				owner: string;
				repo: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['AuthorizationRequest'];
			};
		};
		responses: {
			/** @description Live authorization context for the verified user. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Authorization'];
				};
			};
			400: components['responses']['Error'];
			401: components['responses']['Error'];
			403: components['responses']['Error'];
			503: components['responses']['Error'];
		};
	};
}

type ReadonlyArray<T> = [Exclude<T, undefined>] extends [unknown[]]
	? Readonly<Exclude<T, undefined>>
	: Readonly<Exclude<T, undefined>[]>;
export const healthStatusValues: ReadonlyArray<components['schemas']['Health']['status']> = ['ok'];
export const sessionStateValues: ReadonlyArray<components['schemas']['Session']['state']> = [
	'disabled',
	'signed_out',
	'authenticated'
];
export const actionValues: ReadonlyArray<components['schemas']['Action']> = [
	'assign_comment',
	'bootstrap_pull_request'
];
export const errorCodeValues: ReadonlyArray<components['schemas']['Error']['code']> = [
	'invalid_request',
	'reconnect_required',
	'forbidden',
	'forgery_rejected',
	'identity_unavailable',
	'not_found',
	'method_not_allowed'
];
